### ISSUE TITLE
Improve usability of "cancel funding" interaction

### ISSUE THREAD

**Issue by tomomiq** [cobudget-org/cobudget#358]
In response to the incident last week where a user accidentally deleted a bucket, here's our proposal to make it less likely / problematic: 

1. Change wording from "Cancel funding" to "Cancel bucket" 
2. Enrich the warning popup 
3. Make it a revertible soft delete 

What do you think? 

For reference, here is the current cobudget popup, where the severity of the warning is quite stronger. 
 
![Image 2021-10-19 at 3 10 58 PM](https://user-images.githubusercontent.com/1287179/137916415-b88df650-a02f-453f-8d9a-dd7616477427.jpg)

**Comment by aerugo** [comment]
> Make it a revertible soft delete

What do we mean by this @tomomiq? 

Do we mean that you can "cancel the cancelation" of the funds you have received?
That might be hard to implement. For example, consider this workflow:

1) Bob creates a bucket and starts accepting funds.
2) Lisa funds Bobs bucket with 100 EUR.
3) Bob accidentally cancels the funding of his bucket.
4) Lisa gets her 100 EUR back and spends them on Sarah's bucket.
5) Bob realizes his mistake and wants to revert it.

What happens to the money that Lisa has now given to Sarah?

I think that this will become too complicated to deal with. I suggest that we need to make cancelations final.

However, in the database, we could still keep the transaction row where Lisa funded Bobs bucket, but it should be toggled to "cancelled" and not counted towards any total. This would then simply be for logging purposes.

**Comment by Powersource** [comment]
Just now thinking about how funny it is that the user has two buttons, "Cancel" and "Yes, cancel it" :rofl: we have very similar in the new cobudget as well, you have "Cancel" and "OK" when the user is asked if they want to cancel it. Just an observation though, I think the highlighting of the confirm button makes it clear enough in practice probably.

**Comment by eden-gt** [comment]
looks great to me !
