### ISSUE TITLE
Decimal error 

### ISSUE THREAD

**Issue by aerugo** [cobudget-org/cobudget#454]
There is a decimal error in the budget table that was not present in the version that is live on dreams.wtf.

**Steps to reproduce:**

* Create a bucket with both costs and existing funds.

**Results:** 

Existing funds are multiplied by 100 in the total.

On new cobudget.com deployment:
<img width="944" alt="Screenshot 2021-11-25 at 12 57 15" src="https://user-images.githubusercontent.com/7785081/143438227-76ef00cc-0ce7-4545-adb9-ab99f8e3d038.png">

On dreams.wtf:
<img width="910" alt="Screenshot 2021-11-25 at 12 58 08" src="https://user-images.githubusercontent.com/7785081/143438252-b902bd3e-331c-4c98-a9c3-cf5dfd5bc299.png">

**Comment by aerugo** [comment]
This is odd @gustavlrsn and @Powersource, were not all changes to master merged into this branch though https://github.com/cobudget-org/cobudget/pull/447 ?

**Comment by Powersource** [comment]
It was quite a mess to merge because the diff was so different. So sort of expected some bug like this. Should be an easy fix.

**Comment by Powersource** [comment]
the merge actually looked like it was done properly but something else changed around the cent stuff. pushed a fix now anyway
