### ISSUE TITLE
[FEATURE] Add notification email for successful direct funding allocation

### ISSUE THREAD

**Issue by francesca-sp** [cobudget-org/cobudget#824]
**Describe the feature**
When a user contributes to a bucket with the direct funding feature, send them a notification email confirming the transaction was successful (ideally with a receipt!). Based on the options, either send this through Stripe directly (if that is possible, this might make the receipt option available), or otherwise add a new notification email sent by cobudget that gets triggered. 

If we go for option 2, I can propose some copy.

**Comment by aerugo** [comment]
Let’s do a notification email through cobudget. @francesca-sp could you propose the copy?

**Comment by francesca-sp** [comment]
@aerugo here it is! https://github.com/cobudget/cobudget/issues/827

This is the same notification, right?

**Comment by Powersource** [comment]
Seems like the same issue
